version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:admin@host.docker.internal/EcomAppDatabase
    # No longer depends on db service since we're using the host's PostgreSQL